env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - babel
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-const-assign:
    - warn
  no-unused-vars:
    - warn
  no-console:
    - warn
  arrow-parens: 
    - as-needed
